# Jekyll configuration

# Name of your site (this will show up at the top of your page and in the RSS feed)
name: ElkArte Themes

# Short description (goes below the title; it will also be used in the RSS feed)
description: Themes to customize the way your forum looks and feels.

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
#baseurl: 'http://spuds.github.io/themes'
baseurl: 'http://themes.elkarte.net'
#baseurl: ''

# This can be '' to hide the Github nav button
github: 'elkarte/themes'

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: ''

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: ''
comments: false

permalink: /:year/:month/:title
paginate: 5

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables"]

kramdown:
  input: GFM

exclude: [vendor]
